language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t velhoarchitect/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true velhoarchitect/docker-react npm run test